apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation
  template:
    metadata:
      labels:
        app: moderation
    spec:
      containers:
        - name: moderation
          image: uzukwujp/moderation:latest
          ports:
          - containerPort: 3000
          env:
            - name: clusterId
              value: bloging

            - name: url
              value: 'http://nats-srv:4222'
              
            - name: clientId
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name 
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-srv
spec:
  selector:
    app: moderation
  ports:
    - name: moderation
      protocol: TCP
      port: 3000
      targetPort: 3000