name: tests-post

on:
  pull_request:
    paths:
      - 'post/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd post && npm install && npm run test