name: tests-query

on:
  pull_request:
    paths:
      - 'query/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd query && npm install && npm run test
